version: '3'

services:
  web:
    build: .
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery

  celery:
    build: .
    command: ["celery", "-A", "tanxfi_task", "worker", "-l", "info"]
    depends_on:
      - redis

  celery-beat:
    build: .
    command: ["celery", "-A", "tanxfi_task", "beat", "-l", "info"]
    depends_on:
      - redis

  redis:
    image: "redis:latest"
