# Generated by Django 4.2.7 on 2024-04-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletDetails',
        ),
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
