# Generated by Django 4.2.7 on 2024-04-09 03:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('btcc', '0005_alter_wallet_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='locked_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet',
            field=models.CharField(choices=[('BTC', 'BTC'), ('ETH', 'ETH'), ('DOGE', 'DOGE'), ('USDT', 'USDT')], max_length=10),
        ),
    ]
