# Generated by Django 4.2.7 on 2024-04-04 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptocurrency', models.CharField(max_length=50)),
                ('target_price', models.FloatField()),
                ('status', models.CharField(choices=[('created', 'Created'), ('deleted', 'Deleted'), ('triggered', 'Triggered')], default='created', max_length=20)),
            ],
        ),
    ]
